version: '3'
services:
   annotate:
      build: .
      ports:
         - "${ANNOTATE_PORT:-8888}:${ANNOTATE_PORT:-8888}"
      volumes:
         - ${PWD}/src:/src
         - ${PWD}/save:/save
         - ${PWD}/cache:/cache
         - ${PWD}/config:/config
         - ${PWD}:/git
         - ${ANNOTATE_DATA_PATH:-/opt/freesurfer/subjects}:/data
      environment:
        - DOCKER_STACKS_JUPYTER_CMD=notebook
        - JUPYTER_PORT=${ANNOTATE_PORT:-8888}
