################################################################################
# This file contains the configuration for the cortex-annotate toolkit. By
# editing this file, one can configure cortex-annotate to work with various
# datasets and to enable annotation of specific contours, points, and
# boundaries. The current contents of this file configure the tool for
# annotation of the visual cortex of subjects in the NYU retinotopy dataset.


display:
  figsize: [4, 4]
  dpi: 128
  plot_options:
    color: "#dbfbff"
    linewidth: 1
    markersize: 1
    linestyle: "solid"
  fg_options:
    color: [1, 1, 1]
    markersize: 2

init: |
  # Several code-blocks in this config.yaml file use the numpy and neuropythy
  # libraries, so we load them here.
  import numpy as np
  import neuropythy as ny
  # We also want to create an object that tracks the S3 path/data for the NSD.
  # We use the cache path '/cache/nsd' because the /cache directory is always
  # abailable for use with cache files inside of the docker container that runs
  # the annotation tool.
  nsd_path = ny.util.pseudo_path(
      's3://natural-scenes-dataset/nsddata/',
      cache_path='/cache/nsd')
  # We will specifically load these population receptive fields (pRF) files in
  # order to draw visual area annotations on the retinotopic maps for each
  # subject.
  nsd_prf_files = {
      "polar_angle": "prfangle.mgz",
      "eccentricity": "prfeccentricity.mgz",
      "prf_cod": "prfR2.mgz",
      "wang15": "Kastner2015.mgz",
      "sulc": "corticalsulc.mgz"}
  nsd_votc_files = {
      "faces": "flocfacestval.mgz",
      "places": "flocplacestval.mgz",
      "characters": "floccharacterstval.mgz",
      "bodies": "flocbodiestval.mgz",
      "objects": "flocobjectstval.mgz",
      "floc_cod": "flocR2.mgz",
      "wang15": "Kastner2015.mgz",
      "csulc": "corticalsulc.mgz"}
  # This occipital pole mask is used with neuropythy's flatmap code; the tuple
  # indicates that the FreeSurfer parcellation property uses the value 43 to
  # indicate the occipital pole of the brain.
  occpole_mask = ('parcellation', 43)
  # This function converts a property into a boundary based on what is on either
  # side of the boundary.
  def prop_to_boundary(target, mask1, mask2=None):
      fmap = target['flatmap']
      (u,v) = fmap.tess.indexed_edges
      umask = np.zeros(fmap.vertex_count, dtype=bool)
      umask[fmap.mask(mask1, indices=True)] = True
      if mask2 is None:
        vmask = ~umask
      else:
        vmask = np.zeros(fmap.vertex_count, dtype=bool)
        vmask[fmap.mask(mask2, indices=True)] = True
      ii = (umask[u] & vmask[v]) | (umask[v] & vmask[u])
      xy = fmap.coordinates
      dat = (xy[:,u[ii]] + xy[:,v[ii]]) / 2
      return [dat.T]

# We assume in this example that the libraries neuropythy and numpy have been
# imported (as ny and np respectively) in the init section (see below).
targets:
  # The NSD contains 8 subjects, listed below. The 'Subject ID' entry will be
  # a dropdown menu in the annotation tool because it is a list of multiple
  # choices rather than a code-block or a list with a single entry.
  Subject ID:
    - subj01
    - subj02
    - subj03
    - subj04
    - subj05
    - subj06
    - subj07
    - subj08
  # The 'subject' entry is a multi-line string, so it is interpreted as a Python
  # code snippet. This snippet is compiled into a function whose parameter list
  # contains only the variable `target`. The `target` will be a dictionary with
  # the target data above the subject, so in this case only the 'Subject ID'.
  subject: |
    # Get the subject ID that the user chose from the above selection list.
    sid = target['Subject ID']
    # Find a sub-path for the subject's FreeSurfer directory; we get the
    # nsd_path variable from the `init` section of the config.yaml file; see
    # above.
    fs_path = nsd_path.subpath('freesurfer', sid)
    # Load and return a FreeSurfer subject object for this path.
    return ny.freesurfer_subject(fs_path)
  # The 'Hemisphere' is a choice for the user; as a list of two options, it will
  # appear as a dropdown meny with these two options in the annotation tool.
  Hemisphere:
    - LH
    - RH
  # The 'cortex' key in the target data is for the cortical surface object,
  # which is managed and loaded by neuropythy from the subject's FreeSurfer
  # object. Note that the 'cortex' entry is like the 'subject' entry in that it
  # is compiled into a function whose only parameter is a dict object called
  # `target`, but because it is farther down in the target section, the `target`
  # parameter will contain entries for 'Subject ID', 'subject', and 'Hemisphere'
  # from the sections above.
  cortex: |
    # Extract the subject object and the hsmisphere name.
    sid = target['Subject ID']
    sub = target['subject']
    h = target['Hemisphere'].lower()
    # Load retinotopic mapping data from the label directory, where these data
    # are stored on the NSD repository.
    label_path = nsd_path.subpath('freesurfer', sid, 'label')
    props = {
        k: ny.load(label_path.subpath(f'{h}.{filename}'))
        for (k,filename) in nsd_votc_files.items()}
    # Convert the polar angle into Neuropythy's "visual" format (i.e., 0 degrees
    # is the upper vertical meridian, 90 degrees is the right horizontal
    # meridian, and -90 degrees is the left horizontal meridian.
    if "polar_angle" in props:
        ang = props['polar_angle']
        props['polar_angle'] = np.mod(90 - ang + 180, 360) - 180
    # Grab the appropriate coretx/hemisphere object.
    cortex = sub.hemis[h]
    # Finally, return that hemisphere object with the properties associated with
    # it (this is Neuropythy's typical modus operandi for adding properties to
    # existing objects: make a copy with the properties attached).
    return cortex.with_prop(props)
  # Finally, we include a 'flatmap' entry of the `targets` section in order to
  # create a flattened projection of the hemisphere for annotation. We use the
  # `mask_flatmap` method of the cortex/hemisphere object in order to create a
  # projection of the inflated native surface that is centered on the occipital
  # pole. This uses the `occpole_mask` defined in the `init` section above.
  flatmap: |
    cortex = target['cortex']
    return cortex.mask_flatmap(occpole_mask, map_right='right', radius=np.pi/2)

builtin_annotations:
  Wang2015 Atlas:
    type: points
    plot_options:
      color: [1, 1, 0]
      markersize: 1
      visible: false
    data: |
      fmap = target['flatmap']
      (u,v) = fmap.tess.indexed_edges
      w = fmap.prop('wang15')
      xy = fmap.coordinates
      ii = w[u] != w[v]
      dat = np.mean([xy[:,u[ii]], xy[:,v[ii]]], axis=0)
      return [dat.T]
  IOG:
    type: points
    plot_options:
      color: [0.8, 0.2, 0.2]
      markersize: 1
      visible: true
    data: |
      return prop_to_boundary(target, ('csulc', 2))
  FG:
    type: points
    plot_options:
      color: [0.7, 0.7, 0.7]
      markersize: 1
      visible: false
    data: |
      return prop_to_boundary(target, ('csulc', 3))
  CS:
    type: points
    plot_options:
      color: [0.7, 0.7, 0.7]
      markersize: 1
      visible: false
    data: |
      return prop_to_boundary(target, ('csulc', 4))
  IFG:
    type: points
    plot_options:
      color: [0.7, 0.7, 0.7]
      markersize: 1
      visible: false
    data: |
      return prop_to_boundary(target, ('csulc', 5))
  Calc:
    type: points
    plot_options:
      color: [0.7, 0.7, 0.7]
      markersize: 1
      visible: false
    data: |
      return prop_to_boundary(target, ('csulc', 6))
  OTS:
    type: points
    plot_options:
      color: [0.7, 0.7, 0.7]
      markersize: 1
      visible: true
    data: |
      return prop_to_boundary(target, ('csulc', 7))
  mFus:
    type: points
    plot_options:
      color: [1, 0.4, 0.4]
      markersize: 1
      visible: true
    data: |
      return prop_to_boundary(target, ('csulc', 8))
  LOS:
    type: points
    plot_options:
      color: [0.2, 1, 1]
      markersize: 1
      visible: true
    data: |
      return prop_to_boundary(target, ('csulc', 23))
  TOS:
    type: points
    plot_options:
      color: [0.7, 0.7, 0.7]
      markersize: 1
      visible: false
    data: |
      return prop_to_boundary(target, ('csulc', 24))
  CoS:
    type: points
    plot_options:
      color: [0.1, 1.0, 0.1]
      markersize: 1
      visible: true
    data: |
      return prop_to_boundary(target, ('csulc', 25))
  ITS:
    type: points
    plot_options:
      color: [0.7, 0.7, 0.7]
      markersize: 1
      visible: false
    data: |
      return prop_to_boundary(target, ('csulc', 26))
  ptCoS:
    type: points
    plot_options:
      color: [0.7, 0.7, 0.7]
      markersize: 1
      visible: false
    data: |
      return prop_to_boundary(target, ('csulc', 27))
  POS:
    type: points
    plot_options:
      color: [0.7, 0.7, 0.7]
      markersize: 1
      visible: false
    data: |
      return prop_to_boundary(target, ('csulc', 28))
      
annotations:
  LOS-bodies:
    - ["bodies"]
    - ["curvature"]
  pFus-faces:
    - ["faces"]
    - ["curvature"]
  CoS-places:
    - ["places"]
    - ["curvature"]

figures:
  term: |
    xy = target['flatmap'].coordinates
    (xmin,ymin) = np.min(xy, axis=1)
    (xmax,ymax) = np.max(xy, axis=1)
    axes.set_xlim((xmin,xmax))
    axes.set_ylim((ymin,ymax))
  _: |
    ny.cortex_plot(
        target['flatmap'], color=key, axes=axes,
        cmap='temperature_dark', vmin=-8, vmax=8)
  polar_angle: |
    ny.cortex_plot(target['flatmap'], color="polar_angle", axes=axes)
  eccentricity: |
    ny.cortex_plot(target['flatmap'], color="eccentricity", axes=axes)
  prf_cod: |
    ny.cortex_plot(target['flatmap'], color="prf_cod", axes=axes,
                   cmap='hot', vmin=0, vmax=100)
  curvature: |
    ny.cortex_plot(target['flatmap'], axes=axes)
